ALTER TABLE orders ADD COLUMN IF NOT EXISTS items_summary TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_amount FLOAT DEFAULT 0.0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS route_path JSONB;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS eta_minutes INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
